### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stfalcon** [newagebegins/BattleCity#1]
Hi! Great work!

To the point, what License are you releasing this code under? GPL? MIT-Style?

**Comment by Trilarion** [comment]
Hi, nice game. Just for clarification, can the MIT license text also be added to the repo. For example by copying from https://en.wikipedia.org/wiki/MIT_License#License_terms and storing in a LICENSE.md file or similar and maybe mention MIT in the README. That would make the code license situation more clear. Many thanks.

**Comment by newagebegins** [comment]
Hi! Added LICENSE
